#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/fusegen
  
  blListGen \
    -d ../fusegen \
    -1L  \
    -u $DVCZ_UDIR \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
