#! /usr/bin/env python3

import os, sys
from fusegen import FIRST_LINES, FuseFunc

lines = []

with open(FIRST_LINES, 'r') as f:
    line = f.readline()
    while line and line != '':
        line = line[:-1]
        lines.append(line)
        # DEBUG
        #print(line)
        #
        line = f.readline()

for line in lines:
    name, ff = FuseFunc.parseProto(line, 'zzz')
