#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/fusegen
  
  autopep8 -ai -r fusegen fuseDecode fuseGen *.py
  echo "not styling bin/ subdir"
  echo "not styling fragments/ subdir"
  echo "not styling src/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
