#!/usr/bin/python3

import os
import struct
import sys
from argparse import ArgumentParser
# XXX we want to drop OP_NAMES
from fusegen import __version__, __version_date__, OP_NAMES, FuseFunc
from optionz import dump_options


def decode(chunk):
    sec, nsec, late_n_sec, byte0, byte1, byte2, op_code = \
        struct.unpack('IIIBBBB', chunk)
    # DEBUG
    #print("%3d %3d %3d %3d" % (byte0, byte1, byte2, opCode))
    # END
    late_sec = 0x3f & byte0             # low-order 7 bits
    low_bit = (byte0 >> 7) & 1         # high-order bit from that byte
    higher_bits = (byte1 + (byte2 << 8)) << 1
    byte_count = higher_bits | low_bit

    return sec, nsec, late_sec, late_n_sec, byte_count, op_code


def do_counts(args):
    """ generate a table showing how often each opcode ws invoked """
    how_many = args.how_many
    path = args.pathToData
    verbose = args.verbose
    zeroes = args.zeroes

    with open(path, 'rb') as file:
        data = file.read()
    byte_count = len(data)
    op_count = byte_count / 16
    if verbose:
        print("%d bytes, %d ops" % (byte_count, op_count))

    _, op_code_map = FuseFunc.get_func_map()

    # XXX WORKING HERE XXX
    _ = op_code_map             # supress warnings

    table = [0] * len(OP_NAMES)
    for ndx in range(how_many):
        begin = ndx * 16
        end = begin + 16
        chunk = data[begin:end]
        sec, nsec, late_sec, late_n_sec, byte_count, op_code = decode(chunk)
        table[op_code] += 1

    my_map = {}
    for ndx, name in enumerate(OP_NAMES):
        my_map[name] = (ndx, table[ndx])

    # header line
    non_zeroes = 0    # index of opcodes with non-zero count
    print("ndx opCode name                count")
    for name in sorted(OP_NAMES):
        ndx, count = my_map[name]
        if (zeroes and count == 0) or ((not zeroes) and count > 0):
            print("%3d  %4d  %-16s   %6d" % (non_zeroes, ndx, name, count))
            non_zeroes += 1


def simple_dump(args):
    # column headers
    print("==== op time === == latency == = byte = == opcode ==     = flags =")
    print("  sec   nanosec  sec  nanosec   count   op   name")

    how_many = args.how_many
    path = args.pathToData
    verbose = args.verbose

    with open(path, 'rb') as file:
        data = file.read()
    byte_count = len(data)
    op_count = byte_count / 16
    if verbose:
        print("%d bytes, %d ops" % (byte_count, op_count))
    last_sec = 0
    last_n_sec = 0
    last_late_sec = 0
    last_late_n_sec = 0
    for ndx in range(how_many):
        flag = ''                          # 'P' if concurrency detected
        begin = ndx * 16
        end = begin + 16
        chunk = data[begin:end]
        sec, nsec, late_sec, late_n_sec, byte_count, op_code = decode(chunk)
        if sec == last_sec and nsec < last_n_sec + last_late_n_sec:
            flag = 'P'
        print("%6d %9d %2d %9d %7d   %2d %-16s %s" % (
            sec, nsec, late_sec, late_n_sec,
            byte_count, op_code, OP_NAMES[op_code], flag))
        last_sec = sec
        last_n_sec = nsec
        last_late_sec = late_sec
        last_late_n_sec = late_n_sec


def do_run(args):
    counting = args.stats
    if counting:
        do_counts(args)
    else:
        simple_dump(args)


def main():
    desc = 'parse a fuseGenned data file'
    parser = ArgumentParser(description=desc)

    parser.add_argument('-D', '--pathToData',
                        help='path to data file')

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show options and exit')

    parser.add_argument('-n', '--how_many', type=int, default=0,
                        help='how many data points to decode')

    parser.add_argument('-S', '--stats', action='store_true',
                        help='be chatty')

    parser.add_argument('-v', '--verbose', action='store_true',
                        help='be chatty')

    parser.add_argument('-z', '--zeroes', action='store_true',
                        help='list only zero-count opcodes')

    args = parser.parse_args()

    # sanity checks -------------------------------------------------
    if not os.path.exists(args.pathToData):
        print("%s does not exist; aborting" % args.pathToData)
        sys.exit(1)

    # fixups --------------------------------------------------------
    file_size = os.path.getsize(args.pathToData)
    item_count = int(file_size / 16)
    if item_count * 16 != file_size:
        print("warning: file size is not a multiple of 16")
    if args.how_many > item_count or args.how_many == 0:
        args.how_many = item_count

    # sanity checks -------------------------------------------------
    if args.how_many <= 0:
        print("%d is not a positive integer" % args.how_many)
        sys.exit(1)

    # complete setup ------------------------------------------------
    app_name = 'fuse_decode %s' % __version__

    # maybe show options and such -----------------------------------
    if args.verbose or args.justShow:
        print("%s %s" % (app_name, __version_date__))

    if args.verbose or args.justShow:
        print(dump_options(args))

    if not args.justShow:
        do_run(args)


if __name__ == '__main__':
    main()
